### PR TITLE
Update 10up-toolkit to version 4.3 and update blocks to use `useBlockAssets` feature

### PR DESCRIPTION
**Pull request by fabiankaegy**
in version 4.2 of toolkit the way block assets get handled got updated to use asset keys from the individual block.json file for entrypoint management

See: 10up/10up-toolkit#195

### CODE REVIEW

**Comment by fabiankaegy** [comment]
I'm leaving this as a Draft PR till the final version of 4.2 gets released.

CC: @nicholasio @Antonio-Laguna

**Comment by joesnellpdx** [comment]
@fabiankaegy can we add this PR to the 4.2 update? https://github.com/10up/wp-scaffold/pull/164
The regex works as expected. Thanks !

**Review by nicholasio — APPROVED** [review]

**Comment by fabiankaegy** [comment]
Thanks for the 👍 

My plan currently is to add something to the toolkit docs about this, update the Gutenberg training with this new approach, and include this in a blog post.

**Comment by fabiankaegy** [comment]
This is the PR to update the docs of toolkit: https://github.com/10up/10up-toolkit/pull/247

**Pull request merged**
