### PR TITLE
Update Node version to 16

### LINKED ISSUE #73: Upgrade to `node v16`
### Is your enhancement related to a problem? Please describe.

We should use `node v16` by default. Internal communications - https://10up.slack.com/archives/C105936H3/p1642701456049200

### Designs

_No response_

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by fabiankaegy**
### Description of the Change
Update the node version to `16`. See: https://10up.slack.com/archives/C105936H3/p1642701456049200

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Credits

Props @

### CODE REVIEW

**Review by nicholasio — APPROVED** [review]

**Comment by joesnellpdx** [comment]
@nicholasio @rdimascio @fabiankaegy 

Toolkit [2.0.0 has been released](https://github.com/10up/10up-toolkit/releases/tag/10up-toolkit%402.0.0). Do we need to do any additional testing with this PR / update in reference to toolkit?

**Comment by rdimascio** [comment]
I think we should also update the [theme](https://github.com/10up/wp-scaffold/blob/d65c8f5913ad57cfb491407d42acbf0f296427a1/themes/10up-theme/package.json#L15) and [plugin](https://github.com/10up/wp-scaffold/blob/d65c8f5913ad57cfb491407d42acbf0f296427a1/mu-plugins/10up-plugin/package.json#L15) node versions.

We have an `.npmrc` file with `engine-strict=true` in the root folder, do we need this file in the theme and plugin directories as well?

I would also suggest upgrading to toolkit@2.0 but unsure whether that makes sense in a separate PR.

**Comment by nicholasio** [comment]
@joesnellpdx No additional testing is needed for upgrading to node 16 when it comes to 10up-toolkit.

I agree that we should update node version to 16 everywhere (themes and plugins). I'd also include npm >= 7 in the engines section of package.json.

**Comment by nicholasio** [comment]
10up-toolkit v2 updated in https://github.com/10up/wp-scaffold/pull/82

**Pull request merged**
