### PR TITLE
Fix: Escaping of block wrapper attributes function

### PR DESCRIPTION
**Pull request by fabiankaegy**
Removes the incorrect triple escaping of the `get_block_wrapper_attributes` function

### CODE REVIEW

**Review by christianc1 — APPROVED** [review]
This looks good, we're removing a bunch of superfluous escaping.

**Comment by christianc1** [comment]
@cameronterry : Have a look see.

**Comment by fabiankaegy** [comment]
@cameronterry tagging you here since Christian mentioned you brought this up originally :)

**Comment by cameronterry** [comment]
@fabiankaegy I don't recall git blame working this way :sweat_smile:

Looks good to me :+1: - thanks Fabian!

**Pull request merged**
