### PR TITLE
Add skip to content link

### PR DESCRIPTION
**Pull request by AlejandroPerezMartin**
This PR adds a skip to content link to improve accessibility as described in: https://www.w3.org/TR/WCAG20-TECHS/G1.html (Requirement in WCAG 2.0).

### Benefits

Improve accessibility for keyboard-only users.

### Verification Process

- The _Skip to content_ link should be invisible until it gets focused.
- Press `Tab` and the link should now be visible.
- Pressing enter or clicking that button should change the focus to the main content area (#39 

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

ADDED: Skip to content link

### CODE REVIEW

**Comment by AlejandroPerezMartin** [comment]
This is pending https://github.com/10up/wp-scaffold/pull/43 as the values may change depending on the base font size

**Comment by dmtrmrv** [comment]
Hey @AlejandroPerezMartin @joesnellpdx let me propose a few changes to this PR:

1. I was never a fan of the class name `screen-reader-text` as it is a bit misleading. Technically all text on the screen that's not hidden from screen readers is a screen reader text. What we are doing with `screen-reader-text` is kind of the opposite, we are visually hiding an element but making it accessible to screen readers. With that said, I think we should call it `visually-hidden`.

2. I also think we should introduce two utility classes instead of one: `visually-hidden` and `visually-hidden-focusable`. First one does not require a focused state and is useful for things like:

```
<a href="#">Learn more <span class="visually-hidden">about {{articleTitlte}}</span></a>
```
... and the second for things like the _skip to content_ link.

3. Speaking of the _skip to content link_. I think it should be a separate component in CSS. `screen-reader-text` (or `visually-hidden-focusable`) class is meant to be used as a utility class, so applying styles meant only for _skip to content link_ to its focused state isn't correct. Most likely other elements with this class will need different position, font size, background and padding. We'll have to override those every time we use this class, which isn't productive.

For reference, I made proposed changes in this branch: https://github.com/10up/wp-scaffold/tree/feature/skip-to-content-link-updates

Feel free to compare these branches and let me know if you have any questions. Thanks!

**Comment by AlejandroPerezMartin** [comment]
All your points makes sense to me @dmtrmrv ! Could you please open a new PR? Then I'll close this one! Thanks a lot! 😄

cc @joesnellpdx

**Comment by dmtrmrv** [comment]
@AlejandroPerezMartin the new PR is here #47 We can close this one.

**Comment by AlejandroPerezMartin** [comment]
thanks @dmtrmrv!

**Pull request closed without merging**
